"""Initial migration

Revision ID: 212447c5edd3
Revises: 
Create Date: 2023-09-04 23:04:51.597205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212447c5edd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='Время создания записи'),
    sa.Column('modified', sa.DateTime(), nullable=False, comment='Время изменения записи'),
    sa.Column('age', sa.Integer(), nullable=False, comment='Возраст пользователя'),
    sa.Column('first_name', sa.String(), nullable=False, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(), nullable=False, comment='Второе имя пользователя'),
    sa.Column('country', sa.String(), nullable=False, comment='Страна пользователя'),
    sa.Column('city', sa.String(), nullable=False, comment='Город пользователя'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile')),
    sa.UniqueConstraint('id', name=op.f('uq_user_profile_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
