"""initial migrate

Revision ID: 6805fe5831fa
Revises: 
Create Date: 2023-09-09 22:29:07.119785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6805fe5831fa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genre",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Идентификатор жанра"),
        sa.Column("name", sa.String(), nullable=False, comment="Название жанра"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_genre")),
        sa.UniqueConstraint("id", name=op.f("uq_genre_id")),
        sa.UniqueConstraint("name", name=op.f("uq_genre_name")),
    )
    op.create_table(
        "user_profile",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Идентификатор пользователя"),
        sa.Column("created", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column("modified", sa.DateTime(), nullable=False, comment="Время изменения записи"),
        sa.Column("age", sa.Integer(), nullable=False, comment="Возраст пользователя"),
        sa.Column("first_name", sa.String(), nullable=False, comment="Имя пользователя"),
        sa.Column("last_name", sa.String(), nullable=False, comment="Второе имя пользователя"),
        sa.Column("country", sa.String(), nullable=False, comment="Страна пользователя"),
        sa.Column("city", sa.String(), nullable=False, comment="Город пользователя"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profile")),
        sa.UniqueConstraint("id", name=op.f("uq_user_profile_id")),
    )
    op.create_table(
        "user_profile_genre",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Идентификатор связи пользователя и жанра"
        ),
        sa.Column("created", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column("modified", sa.DateTime(), nullable=False, comment="Время изменения записи"),
        sa.Column("user_id", sa.Uuid(), nullable=False, comment="Идентификатор пользователя"),
        sa.Column("genre_id", sa.Uuid(), nullable=False, comment="Идентификатор жанра"),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genre.id"],
            name=op.f("fk_user_profile_genre_genre_id_genre"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profile.id"],
            name=op.f("fk_user_profile_genre_user_id_user_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profile_genre")),
        sa.UniqueConstraint("id", name=op.f("uq_user_profile_genre_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profile_genre")
    op.drop_table("user_profile")
    op.drop_table("genre")
    # ### end Alembic commands ###
